FROM maven:3.9.9-sapmachine-21 AS build

WORKDIR /4

COPY pom.xml .
COPY src ./src

RUN mvn clean package

FROM openjdk:21-oracle

WORKDIR /

COPY --from=build /4/target/4-1.0-SNAPSHOT-jar-with-dependencies.jar app.jar

COPY --from=build /4/src ./4/src

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
